### PR TITLE
Add eslint and fix basic linting errors

### PR DESCRIPTION
**Pull request by THPubs**
just enabled `.eslint` with airbnb style guide.

Also used atom's eslint fix tool to fix some linting issues. But some still remain which needs manual review to fix 😄

### CODE REVIEW

**Comment by kasunben** [comment]
@THPubs Awesome! 👍 

I'll fix those manually. :)

**Comment by THPubs** [comment]
Perfect :smile:

**Comment by kasunben** [comment]
I took these changes into `dev` branch. Will do that lint fix there. :)

**Comment by THPubs** [comment]
Ah perfect thanks! 😄 I'll look into the custom port thing tomorrow.

**Comment by kasunben** [comment]
> I'll look into the custom port thing tomorrow.

Okay, 👍 I'll update an issue for that. I think we just need to define the port when initialize the site. We can keep those settings in `site.json`. 
When the user runs `wp serve` command, it'll run based on settings in there.

In any case, user try to use a custom port, it needs to update on both `site.json`, `wp-config.php` files and the database before start the server.

**Comment by THPubs** [comment]
Hmmm that means the user won't have the option to choose a custom port on runtime with the `--port` flag?

**Comment by kasunben** [comment]
Ah, forgot to mention. :)

How about we keep the`dev` branch for development, and the `master` branch only for final releases. With that we can keep clean codebase. I'll update contribution section for asking all the PR sends to the `dev` branch instead of the `master`. What do you think?

**Comment by THPubs** [comment]
@thinkholic Yeap that's a great idea! It will keep things clean and the way I'm used to 😄

**Comment by kasunben** [comment]
> Hmmm that means the user won't have the option to choose a custom port on runtime with the --port flag?

No no. there is an option flag as `--port` too. But, everytime user try to use a custom port, it needs to update `site.json`, `wp-config.php` and the database before start the server.

**Comment by THPubs** [comment]
@thinkholic Cool! Understood 👍

**Comment by kasunben** [comment]
@THPubs Great!.
I added you as a collaborator for the repo. Please check.

**Comment by THPubs** [comment]
@thinkholic Oh cool thanks! I just accepted it 😸 This will make contributing a lot easier.

**Comment by kasunben** [comment]
@THPubs Created the issue as promised #2   :)

**Comment by kasunben** [comment]
This issue was moved to thinkholic/testtest#2

**Pull request merged**
